/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Conectar.conectar1;
import java.security.Principal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Vyto
 */
public class ListadoFacturas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListadoFacturas
     */
    public ListadoFacturas() {
        initComponents();
        ListadoFacturas(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarfactura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadodeFacturas = new javax.swing.JTable();

        setTitle("Listado Facturas");

        jLabel1.setText("Buscar :");

        buscarfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarfacturaActionPerformed(evt);
            }
        });

        ListadodeFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ListadodeFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListadodeFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListadodeFacturas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarfacturaActionPerformed
        ListadoFacturas(buscarfactura.getText());
    }//GEN-LAST:event_buscarfacturaActionPerformed

    public void ListadoFacturas(String valor)
    {
    DefaultTableModel model;   
    String titulos[] = {"Codigo Factura","Fecha","Estado"};
    String registro[] = new String [3];
    
    String sql = "SELECT concat_ws(' ,', marca, modelo) FROM autos where CONCAT(CODIGO_AUTO,' ',MARCA,' ',MODELO) LIKE '%"+valor+"%'";
    model = new DefaultTableModel(null,titulos);
    
    
      conectar1 cc = new conectar1();
      Connection cn = cc.conexion();
      
    try{
        Statement st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while(rs.next())
        {
          registro[0] = rs.getString("CODIGO_FACTURA");
          registro[1] = rs.getString("FECHA");
          registro[2] = rs.getString("ESTADO");
          model.addRow(registro);
          ListadodeFacturas.setModel(model);
        }
    
    }catch(SQLException ex)
    {
        Logger.getLogger(ListadoAutos.class.getName()).log(Level.SEVERE,null,ex);
    
    }
    
    }
     
    private void ListadodeFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListadodeFacturasMouseClicked
        int fila = ListadodeFacturas.getSelectedRow();
        try
        {
            if(fila == -1)
            {
                JOptionPane.showMessageDialog(null,"Debe seleccionar un registro");
            }else
            EstadoCliente.CodigoFactura.setText(ListadodeFacturas.getValueAt(ListadodeFacturas.getSelectedRow(),0).toString());
      //      IngresarCompra.auto_txt.setText(ListadodeFacturas.getValueAt(ListadodeFacturas.getSelectedRow(),1).toString());
            dispose();
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_ListadodeFacturasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable ListadodeFacturas;
    public static javax.swing.JTextField buscarfactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
